In [3]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 60)
pd.set_option('display.max_rows', 4)

In [4]:
df = pd.read_csv("Census_Denver.csv")

In [5]:
# Drops useless columns
df.columns.tolist()
df = df.drop(df.columns[47:], axis=1)
df = df.drop(df.columns[3:24], axis=1)
df = df.drop(df.columns[0], axis=1)

In [6]:
df.head()

,NBRHD_NAME,POPULATION_2010,AGE_LESS_5,AGE_5_TO_9,AGE_10_TO_14,AGE_15_TO_17,AGE_18_AND_19,AGE_20,AGE_21,AGE_22_TO_24,AGE_25_TO_29,AGE_30_TO_34,AGE_35_TO_39,AGE_40_TO_44,AGE_45_TO_49,AGE_50_TO_54,AGE_55_TO_59,AGE_60_AND_61,AGE_62_TO_64,AGE_65_AND_66,AGE_67_TO_69,AGE_70_TO_74,AGE_75_TO_79,AGE_80_TO_84,AGE_85_PLUS
0,Hampden,17547.0,965.0,783.0,611.0,395.0,359.0,219.0,227.0,942.0,1657.0,1251.0,1095.0,1038.0,1086.0,1307.0,1212.0,494.0,725.0,346.0,479.0,722.0,564.0,524.0,546.0
1,Baker,4879.0,250.0,213.0,169.0,113.0,78.0,37.0,60.0,225.0,707.0,655.0,524.0,351.0,333.0,295.0,320.0,88.0,126.0,54.0,72.0,91.0,47.0,34.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,Cherry Creek,5589.0,168.0,124.0,85.0,36.0,24.0,20.0,33.0,203.0,583.0,451.0,360.0,371.0,308.0,394.0,493.0,249.0,348.0,193.0,228.0,242.0,212.0,202.0,262.0
4,Country Club,3001.0,177.0,240.0,173.0,82.0,46.0,8.0,10.0,61.0,146.0,143.0,229.0,257.0,230.0,240.0,271.0,112.0,175.0,112.0,86.0,94.0,50.0,31.0,28.0

In [7]:
# Merge some columns
df['Years-15-to-19'] = df['AGE_15_TO_17'] + df['AGE_18_AND_19']
df['Years-20-to-24'] = df['AGE_20'] + df['AGE_21'] + df['AGE_22_TO_24']
df['Years-60-to-64'] = df['AGE_60_AND_61'] + df['AGE_62_TO_64']
df['Years-65-to-69'] = df['AGE_65_AND_66'] + df['AGE_67_TO_69']
df.drop(['AGE_15_TO_17', 'AGE_18_AND_19', 'AGE_20', 'AGE_21', 'AGE_22_TO_24',
         'AGE_60_AND_61', 'AGE_62_TO_64', 'AGE_65_AND_66', 'AGE_67_TO_69'], axis=1, inplace=True)

In [8]:
# Rename columns
df = df.rename(columns={'NBRHD_NAME': 'Neighborhood', 'POPULATION_2010': 'Total-neighborhood-population',
                       'AGE_LESS_5': 'Years-0-to-4', 'AGE_5_TO_9': 'Years-5-to-9',
                       'AGE_10_TO_14': 'Years-10-to-14', 'AGE_25_TO_29': 'Years-25-to-29', 
                       'AGE_30_TO_34': 'Years-30-to-34', 'AGE_35_TO_39': 'Years-35-to-39', 
                       'AGE_40_TO_44': 'Years-40-to-44', 'AGE_45_TO_49': 'Years-45-to-49', 
                       'AGE_50_TO_54': 'Years-50-to-54', 'AGE_55_TO_59': 'Years-55-to-59',
                       'AGE_70_TO_74': 'Years-70-to-74', 'AGE_75_TO_79': 'Years-75-to-79', 
                       'AGE_80_TO_84': 'Years-80-to-84', 'AGE_85_PLUS': 'Years-85-plus'}) # Formats names

In [9]:
# Repositioning Columns
cols = df.columns.tolist()
df = df[cols[0:5] + cols[16:18] + cols[5:12] + cols[18:20] + cols[12:15] + cols[15:16]]

df.set_index('Neighborhood', inplace=True) # Neighborhood is now the index
df = df.transpose() # Transpose the dataframe

In [10]:
df

Neighborhood,Hampden,Baker,Washington Park,Cherry Creek,Country Club,Clayton,Skyland,City Park West,Capitol Hill,North Capitol Hill,Civic Center,CBD,Union Station,Five Points,Stapleton,Highland,Globeville,University Park,Cory - Merrill,Washington Park West,Speer,Congress Park,Cole,Sunnyside,Ruby Hill,University,Goldsmith,Virginia Village,DIA,University Hills,...,North Park Hill,South Park Hill,Kennedy,College View / South Platte,Hampden South,Northeast Park Hill,Elyria Swansea,Overland,Cheesman Park,Hilltop,Lincoln Park,Auraria,Belcaro,Windsor,Sloan Lake,Berkeley,Regis,Sun Valley,Wellshire,Jefferson Park,Valverde,Athmar Park,Chaffee Park,Harvey Park,Barnum,Whittier,Montbello,Marston,Fort Logan,Bear Valley
Total-neighborhood-population,17547.0,4879.0,6905.0,5589.0,3001.0,4336.0,3106.0,4844.0,14708.0,5823.0,1577.0,3648.0,4348.0,12712.0,13948.0,8429.0,3687.0,7491.0,3892.0,6393.0,10954.0,10235.0,4651.0,9726.0,9820.0,9375.0,5808.0,12844.0,1165.0,5327.0,...,9382.0,8590.0,4464.0,6498.0,14370.0,7822.0,6401.0,2218.0,7971.0,8190.0,6119.0,705.0,4172.0,12589.0,7238.0,8112.0,3934.0,1448.0,3133.0,2552.0,3941.0,8898.0,3874.0,11525.0,6111.0,4831.0,30348.0,11132.0,8532.0,8889.0
Years-0-to-4,965.0,250.0,500.0,168.0,177.0,432.0,186.0,208.0,190.0,91.0,23.0,50.0,77.0,578.0,1720.0,512.0,328.0,361.0,334.0,369.0,333.0,552.0,433.0,799.0,887.0,331.0,395.0,863.0,128.0,325.0,...,718.0,604.0,391.0,625.0,927.0,628.0,743.0,132.0,210.0,510.0,447.0,1.0,192.0,687.0,546.0,532.0,175.0,339.0,178.0,189.0,438.0,848.0,253.0,982.0,585.0,435.0,3096.0,700.0,490.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Years-80-to-84,524.0,34.0,116.0,202.0,31.0,71.0,85.0,61.0,92.0,42.0,11.0,26.0,84.0,71.0,38.0,135.0,30.0,153.0,86.0,49.0,131.0,96.0,55.0,143.0,163.0,88.0,184.0,332.0,2.0,145.0,...,173.0,99.0,8.0,46.0,366.0,117.0,62.0,23.0,143.0,241.0,55.0,1.0,160.0,690.0,180.0,162.0,67.0,6.0,126.0,10.0,33.0,112.0,81.0,275.0,33.0,63.0,165.0,160.0,260.0,219.0
Years-85-plus,546.0,37.0,127.0,262.0,28.0,47.0,94.0,47.0,59.0,28.0,3.0,16.0,58.0,62.0,26.0,197.0,20.0,271.0,85.0,40.0,225.0,82.0,30.0,141.0,136.0,110.0,257.0,272.0,1.0,234.0,...,157.0,99.0,3.0,41.0,262.0,87.0,46.0,10.0,130.0,350.0,45.0,0.0,176.0,797.0,190.0,234.0,59.0,4.0,138.0,13.0,30.0,119.0,93.0,170.0,54.0,52.0,109.0,122.0,244.0,172.0

In [11]:
df.to_csv('Census_Denver_Changed.csv')