In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 4)

In [2]:
df = pd.read_csv("Census_Vancouver.csv")

In [3]:
# Organizes the into the right columns
df = df.iloc[3:28]
df.columns = df.iloc[0]
df.drop(df.index[0], inplace=True)
df.rename(columns={'Arbutus-Ridge': 'Arbutus Ridge'})
df.drop(['Vancouver CSD (City)', 'CMA of Vancouver'], axis=1, inplace=True)

In [4]:
df

3,nan,Arbutus-Ridge,Downtown,Dunbar-Southlands,Fairview,Grandview-Woodland,Hastings-Sunrise,Kensington-Cedar Cottage,Kerrisdale,Killarney,...,Oakridge,Renfrew-Collingwood,Riley Park,Shaughnessy,South Cambie,Strathcona,Sunset,Victoria-Fraserview,West End,West Point Grey
4,Total population by age groups,"15,910","54,690","21,745","31,445","27,305","33,990","47,470","14,735","28,450",...,"12,440","50,505","21,795","8,805","7,675","12,165","36,285","30,710","44,540","12,795"
5,0 to 4 years,570,"1,840",930,"1,080","1,190","1,625","2,440",510,"1,325",...,350,"2,335","1,195",335,390,365,"1,960","1,155",960,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,80 to 84 years,535,565,405,665,490,885,965,315,635,...,460,"1,085",430,250,200,430,750,860,760,305
27,85 years and over,785,450,425,880,350,685,785,335,610,...,535,820,340,365,300,495,575,965,720,270

In [5]:
df.to_csv("Census_Vancouver_Changed.csv", index=False)